pipeline {
    agent any

    stages {
        stage('Intall Dependencies') {
            steps {
                bat 'npm install'
                bat 'npx playwright install --with-deps chromium'
            }
        }

        stage('Run Tests') {
            steps {
                bat 'npm run test:ci'
            }
        }
    }

    post {
        always {
            junit 'test-results/*.xml'
            archiveArtifacts artifacts: 'playwright-report/**', allowEmptyArchive: true
        }
    }
}
