pipeline {
    agent any

    stages {

        stage('Verify Node') {
            steps {
                bat 'node -v'
                bat 'npm -v'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat 'npm install'
            }
        }

        stage('Wait for Backend') {
            steps {
                bat '''
                node -e "
                const http = require('http');

                function check() {
                    http.get('http://localhost:3000', res => {
                        process.exit(0);
                    }).on('error', () => {
                        setTimeout(check, 1000);
                    });
                }

                check();
                "
                '''
            }
        }

        stage('Unit Tests') {
            steps {
                bat 'npm test'
            }
        }

        stage('Install Playwright Browsers') {
            steps {
                bat 'npx playwright install --with-deps'
            }
        }

        stage('E2E Tests') {
            steps {
                bat 'npm run e2e'
            }
        }

        stage('Build Successful') {
            steps {
                bat 'echo DoIT Pipeline Passed'
            }
        }
    }
}

